name: an_viewmodel
description: "A package for managing ViewModel that depends on an_lifecycle. Similar to Androidx ViewModel."
version: 3.3.0
homepage: https://github.com/aymtools/an_viewmodel/
issue_tracker: https://github.com/aymtools/an_viewmodel/issues

topics:
  - viewmodel
  - view-model
  - viewmodels
  - mvvm

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter


  cancellable: ^2.3.0
  anlifecycle: ^3.2.0
  an_lifecycle_cancellable: ^2.4.0
  weak_collections: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.15
  
  flutter_lints: ^5.0.0

